import { metronicAsset } from "./urls.js";

/** CSS Metronic demo1 — sama seperti `login-5.html` (Metronic v6 classic). */
export const LOGIN_STYLESHEETS: string[] = [
  "css/demo1/pages/general/login/login-5.css",
  "vendors/general/perfect-scrollbar/css/perfect-scrollbar.css",
  "vendors/general/tether/dist/css/tether.css",
  "vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css",
  "vendors/general/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css",
  "vendors/general/bootstrap-timepicker/css/bootstrap-timepicker.css",
  "vendors/general/bootstrap-daterangepicker/daterangepicker.css",
  "vendors/general/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.css",
  "vendors/general/bootstrap-select/dist/css/bootstrap-select.css",
  "vendors/general/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css",
  "vendors/general/select2/dist/css/select2.css",
  "vendors/general/ion-rangeslider/css/ion.rangeSlider.css",
  "vendors/general/nouislider/distribute/nouislider.css",
  "vendors/general/owl.carousel/dist/assets/owl.carousel.css",
  "vendors/general/owl.carousel/dist/assets/owl.theme.default.css",
  "vendors/general/dropzone/dist/dropzone.css",
  "vendors/general/summernote/dist/summernote.css",
  "vendors/general/bootstrap-markdown/css/bootstrap-markdown.min.css",
  "vendors/general/animate.css/animate.css",
  "vendors/general/toastr/build/toastr.css",
  "vendors/general/morris.js/morris.css",
  "vendors/general/sweetalert2/dist/sweetalert2.css",
  "vendors/general/socicon/css/socicon.css",
  "vendors/custom/vendors/line-awesome/css/line-awesome.css",
  "vendors/custom/vendors/flaticon/flaticon.css",
  "vendors/custom/vendors/flaticon2/flaticon.css",
  "vendors/general/@fortawesome/fontawesome-free/css/all.min.css",
  "css/demo1/style.bundle.css",
  "css/demo1/skins/header/base/light.css",
  "css/demo1/skins/header/menu/light.css",
  "css/demo1/skins/brand/dark.css",
  "css/demo1/skins/aside/dark.css",
].map((p) => metronicAsset(p));
